let divMain = document.createElement('div');
    divMain.className = "divMain";   
document.body.append(divMain);

let title = document.createElement('p');
    title.className = "title";
    title.textContent = "RSS Виртуальна клавиатура";
divMain.append(title);

let textarea = document.createElement('textarea');
    textarea.className = "textarea";
    textarea.id = "textarea";
divMain.append(textarea);

let keyboard_doby = document.createElement('div');
    keyboard_doby.className = "keyboard_doby";
divMain.append(keyboard_doby);

let description = document.createElement('p');
    description.className = "description";
    description.textContent = "Клавиатура создана в операционной системе Windows";
divMain.append(description);

let language = document.createElement('p');
    language.className = "language";
    language.textContent = "Для переключения языка комбинация левые shift + alt";
divMain.append(language);


for (i=1; i<=5; i++) {
    let keyboard_row = document.createElement('div');
    keyboard_row.className = "keyboard_row";
    keyboard_doby.append(keyboard_row);
    keyboard_row.classList.add(`keyboard_row${i}`);    
}

let keyboard_row1 = keyboard_doby.querySelector('.keyboard_row1');
for (i=1; i<=14; i++) {
    let keyboard_button = document.createElement('div');
    keyboard_button.className = "keyboard_button";
    keyboard_row1.append(keyboard_button);
    keyboard_button.classList.add(`keyboard_button1_${i}`);    
}

let keyboard_row2 = keyboard_doby.querySelector('.keyboard_row2');
for (i=1; i<=15; i++) {
    let keyboard_button = document.createElement('div');
    keyboard_button.className = "keyboard_button";
    keyboard_row2.append(keyboard_button);
    keyboard_button.classList.add(`keyboard_button2_${i}`);
}

let keyboard_row3 = keyboard_doby.querySelector('.keyboard_row3');
for (i=1; i<=13; i++) {
    let keyboard_button = document.createElement('div');
    keyboard_button.className = "keyboard_button";
    keyboard_row3.append(keyboard_button);
    keyboard_button.classList.add(`keyboard_button3_${i}`);
}

let keyboard_row4 = keyboard_doby.querySelector('.keyboard_row4');
for (i=1; i<=13; i++) {
    let keyboard_button = document.createElement('div');
    keyboard_button.className = "keyboard_button";
    keyboard_row4.append(keyboard_button);
    keyboard_button.classList.add(`keyboard_button4_${i}`);
}

let keyboard_row5 = keyboard_doby.querySelector('.keyboard_row5');
for (i=1; i<=9; i++) {
    let keyboard_button = document.createElement('div');
    keyboard_button.className = "keyboard_button";
    keyboard_row5.append(keyboard_button);
    keyboard_button.classList.add(`keyboard_button5_${i}`);
}

let keyboard_button1_1 = keyboard_doby.querySelector('.keyboard_button1_1');
let ru = document.createElement('span');
    ru.className = "ru";
    keyboard_button1_1.append(ru);
        let casedown = document.createElement('span');
        casedown.className = "casedown";
        casedown.textContent = "ё";
        ru.append(casedown);        
        let caseUp = document.createElement('span');
        caseUp.className = "caseUp";
        caseUp.textContent = "Ё";
        ru.append(caseUp);
        caseUp.classList.add('hidden');
        let caps = document.createElement('span');
        caps.className = "caps";
        caps.textContent = "Ё";
        ru.append(caps);
        caps.classList.add('hidden');
        let shiftcaps = document.createElement('span');
        shiftcaps.className = "shiftcaps";
        shiftcaps.textContent = "ё";
        ru.append(shiftcaps);
        shiftcaps.classList.add('hidden');

let en = document.createElement('span');
    en.className = "en";
    keyboard_button1_1.append(en);
        casedown = document.createElement('span');
        casedown.className = "casedown";
        casedown.textContent = "`";
        en.append(casedown);
        casedown.classList.add('hidden')
        caseUp = document.createElement('span');
        caseUp.className = "caseUp";
        caseUp.textContent = "~";
        en.append(caseUp);
        caseUp.classList.add('hidden');
        caps = document.createElement('span');
        caps.className = "caps";
        caps.textContent = "`";
        en.append(caps);
        caps.classList.add('hidden');
        shiftcaps = document.createElement('span');
        shiftcaps.className = "shiftcaps";
        shiftcaps.textContent = "~";
        en.append(shiftcaps);
        shiftcaps.classList.add('hidden');

let keyboard_button1_2 = keyboard_doby.querySelector('.keyboard_button1_2');
    ru = document.createElement('span');
    ru.className = "ru";
    keyboard_button1_2.append(ru);
                    casedown = document.createElement('span');
                    casedown.className = "casedown";
                    casedown.textContent = "1";
                    ru.append(casedown);        
                    caseUp = document.createElement('span');
                    caseUp.className = "caseUp";
                    caseUp.textContent = "!";
                    ru.append(caseUp);
                    caseUp.classList.add('hidden');
                    caps = document.createElement('span');
                    caps.className = "caps";
                    caps.textContent = "1";
                    ru.append(caps);
                    caps.classList.add('hidden');
                    shiftcaps = document.createElement('span');
                    shiftcaps.className = "shiftcaps";
                    shiftcaps.textContent = "!";
                    ru.append(shiftcaps);
                    shiftcaps.classList.add('hidden');
        
    en = document.createElement('span');
    en.className = "en";
    keyboard_button1_2.append(en);
                casedown = document.createElement('span');
                casedown.className = "casedown";
                casedown.textContent = "1";
                en.append(casedown);
                casedown.classList.add('hidden')
                caseUp = document.createElement('span');
                caseUp.className = "caseUp";
                caseUp.textContent = "!";
                en.append(caseUp);
                caseUp.classList.add('hidden');
                caps = document.createElement('span');
                caps.className = "caps";
                caps.textContent = "1";
                en.append(caps);
                caps.classList.add('hidden');
                shiftcaps = document.createElement('span');
                shiftcaps.className = "shiftcaps";
                shiftcaps.textContent = "!";
                en.append(shiftcaps);
                shiftcaps.classList.add('hidden');

let keyboard_button1_3 = keyboard_doby.querySelector('.keyboard_button1_3');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_3.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "2";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "\"";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "2";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "\"";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_3.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "2";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "@";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "2";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "@";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button1_4 = keyboard_doby.querySelector('.keyboard_button1_4');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_4.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "3";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "№";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "3";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "№";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_4.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "3";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "#";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "3";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "#";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button1_5 = keyboard_doby.querySelector('.keyboard_button1_5');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_5.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "4";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = ";";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "4";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = ";";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_5.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "4";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "$";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "4";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "$";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button1_6 = keyboard_doby.querySelector('.keyboard_button1_6');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_6.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "5";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "%";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "5";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "%";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_6.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "5";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "%";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "5";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "%";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button1_7 = keyboard_doby.querySelector('.keyboard_button1_7');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_7.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "6";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = ":";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "6";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = ":";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_7.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "6";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "^";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "6";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "^";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button1_8 = keyboard_doby.querySelector('.keyboard_button1_8');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_8.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "7";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "?";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "7";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "?";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_8.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "7";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "?";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "7";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "?";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button1_9 = keyboard_doby.querySelector('.keyboard_button1_9');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_9.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "8";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "*";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "8";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "*";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_9.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "8";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "*";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "8";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "*";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button1_10 = keyboard_doby.querySelector('.keyboard_button1_10');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_10.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "9";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "(";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "9";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "(";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_4.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "9";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "(";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "9";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "(";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button1_11 = keyboard_doby.querySelector('.keyboard_button1_11');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_11.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "0";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = ")";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "0";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = ")";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_11.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "0";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = ")";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "0";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = ")";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button1_12 = keyboard_doby.querySelector('.keyboard_button1_12');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_12.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "-";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "_";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "-";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "_";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_12.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "-";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "_";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "-";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "_";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button1_13 = keyboard_doby.querySelector('.keyboard_button1_13');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_13.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "=";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "+";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "=";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "+";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_13.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "=";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "+";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "=";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "+";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button1_14 = keyboard_doby.querySelector('.keyboard_button1_14');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button1_14.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "backspace";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "backspace";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "backspace";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "backspace";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button1_4.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "backspace";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "backspace";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "backspace";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "backspace";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_1 = keyboard_doby.querySelector('.keyboard_button2_1');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_1.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "tab";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "tab";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "tab";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "tab";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_1.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "tab";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "tab";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "tab";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "tab";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_2 = keyboard_doby.querySelector('.keyboard_button2_2');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_2.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "й";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Й";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Й";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "й";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_2.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "q";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Q";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Q";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "q";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_3 = keyboard_doby.querySelector('.keyboard_button2_3');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_3.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ц";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Ц";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Ц";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ц";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_3.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "w";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "W";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "W";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "w";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_4 = keyboard_doby.querySelector('.keyboard_button2_4');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_4.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "у";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "У";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "У";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "у";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_4.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "e";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "E";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "E";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "e";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_5 = keyboard_doby.querySelector('.keyboard_button2_5');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_5.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "к";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "К";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "К";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "к";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_5.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "r";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "R";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "R";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "R";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_6 = keyboard_doby.querySelector('.keyboard_button2_6');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_6.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "е";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Е";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Е";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "е";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_6.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "t";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "T";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "T";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "t";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_7 = keyboard_doby.querySelector('.keyboard_button2_7');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_7.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "н";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Н";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Н";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "н";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_7.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "y";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Y";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Y";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "y";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_8 = keyboard_doby.querySelector('.keyboard_button2_8');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_8.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "г";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Г";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Г";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "г";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_8.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "u";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "U";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "U";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "u";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_9 = keyboard_doby.querySelector('.keyboard_button2_9');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_9.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ш";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Ш";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Ш";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ш";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_9.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "i";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "I";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "I";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "i";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_10 = keyboard_doby.querySelector('.keyboard_button2_10');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_10.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "щ";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Щ";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Щ";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "щ";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_10.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "o";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "O";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "O";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "o";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_11 = keyboard_doby.querySelector('.keyboard_button2_11');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_11.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "з";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "З";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "З";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "з";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_11.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "p";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "P";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "P";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "p";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_12 = keyboard_doby.querySelector('.keyboard_button2_12');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_12.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "х";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Х";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Х";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "х";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_12.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "[";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "{";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "[";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "{";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_13 = keyboard_doby.querySelector('.keyboard_button2_13');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_13.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ъ";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Ъ";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Ъ";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ъ";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_13.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "]";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "}";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "]";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "}";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_14 = keyboard_doby.querySelector('.keyboard_button2_14');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_14.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "\\";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "/";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "\\";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "/";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_14.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "\\";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "|";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "\\";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "|";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button2_15 = keyboard_doby.querySelector('.keyboard_button2_15');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button2_15.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "del";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "del";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "del";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "del";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_15.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "del";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "del";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "del";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "del";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_1 = keyboard_doby.querySelector('.keyboard_button3_1');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_1.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "caps lock";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "caps lock";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "caps lock";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "caps lock";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_1.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "caps lock";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "caps lock";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "caps lock";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "caps lock";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_2 = keyboard_doby.querySelector('.keyboard_button3_2');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_2.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ф";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Ф";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Ф";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ф";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_2.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "a";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "A";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "A";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "a";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_3 = keyboard_doby.querySelector('.keyboard_button3_3');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_3.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ы";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Ы";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Ы";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ы";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_3.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "s";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "S";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "S";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "s";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_4 = keyboard_doby.querySelector('.keyboard_button3_4');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_4.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "в";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "В";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "В";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "в";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_4.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "d";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "D";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "D";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "d";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_5 = keyboard_doby.querySelector('.keyboard_button3_5');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_5.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "а";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "А";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "А";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "а";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_5.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "f";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "F";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "F";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "f";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_6 = keyboard_doby.querySelector('.keyboard_button3_6');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_6.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "п";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "П";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "П";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "п";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_6.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "g";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "G";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "G";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "g";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_7 = keyboard_doby.querySelector('.keyboard_button3_7');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_7.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "р";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Р";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Р";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "р";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_7.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "h";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "H";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "H";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "h";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_8 = keyboard_doby.querySelector('.keyboard_button3_8');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_8.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "о";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "О";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "О";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "о";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_8.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "j";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "J";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "J";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "j";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_9 = keyboard_doby.querySelector('.keyboard_button3_9');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_9.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "л";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Л";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Л";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "л";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_9.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "k";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "K";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "K";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "k";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_10 = keyboard_doby.querySelector('.keyboard_button3_10');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_10.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "д";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Д";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Д";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "д";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_10.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "l";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "L";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "L";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "l";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_11 = keyboard_doby.querySelector('.keyboard_button3_11');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_11.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ж";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Ж";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Ж";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ж";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_11.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = ";";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = ":";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = ";";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = ":";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_12 = keyboard_doby.querySelector('.keyboard_button3_12');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_12.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "э";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Э";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Э";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "э";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_12.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "'";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "\"";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "'caps'";
caps.textContent = "'";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "\"";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button3_13 = keyboard_doby.querySelector('.keyboard_button3_13');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button3_13.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "enter";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "enter";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "enter";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "enter";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button3_13.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "enter";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "enter";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "enter";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "enter";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_1 = keyboard_doby.querySelector('.keyboard_button4_1');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_1.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "shift";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "shift";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "shift";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "shift";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_1.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "shift";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "shift";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "shift";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "shift";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_2 = keyboard_doby.querySelector('.keyboard_button4_2');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_2.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "я";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Я";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "я";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "я";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_2.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "z";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Z";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Z";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "z";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_3 = keyboard_doby.querySelector('.keyboard_button4_3');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_3.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ч";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Ч";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Ч";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ч";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_3.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "x";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "X";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "X";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "x";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_4 = keyboard_doby.querySelector('.keyboard_button4_4');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_4.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "с";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "С";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "С";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "с";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_4.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "c";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "C";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "C";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "c";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_5 = keyboard_doby.querySelector('.keyboard_button4_5');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_5.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "м";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "М";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "М";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "м";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_5.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "v";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "V";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "V";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "v";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_6 = keyboard_doby.querySelector('.keyboard_button4_6');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_6.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "и";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "И";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "И";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "и";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_6.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "b";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "B";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "B";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "b";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_7 = keyboard_doby.querySelector('.keyboard_button4_7');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_7.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "т";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Т";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Т";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "т";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_7.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "n";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "N";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "N";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "n";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_8 = keyboard_doby.querySelector('.keyboard_button4_8');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_8.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ь";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Ь";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Ь";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ь";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_8.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "m";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "M";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "M";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "m";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_9 = keyboard_doby.querySelector('.keyboard_button4_9');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_9.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "б";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Б";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Б";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "б";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_9.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = ",";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "<";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = ",";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "<";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_10 = keyboard_doby.querySelector('.keyboard_button4_10');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_10.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ю";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "Ю";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "Ю";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ю";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_10.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = ".";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = ">";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = ".";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = ">";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_11 = keyboard_doby.querySelector('.keyboard_button4_11');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_11.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = ".";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = ",";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = ".";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = ",";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_11.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "/";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "?";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "/";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "?";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_12 = keyboard_doby.querySelector('.keyboard_button4_12');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_12.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "▲";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "▲";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "▲";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "▲";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_12.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "▲";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "▲";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "▲";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "▲";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button4_13 = keyboard_doby.querySelector('.keyboard_button4_13');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button4_13.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "shift";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "shift";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "shift";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "shift";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button4_13.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "shift";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "shift";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "shift";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "shift";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button5_1 = keyboard_doby.querySelector('.keyboard_button5_1');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button5_1.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ctrl";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "ctrl";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "ctrl";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ctrl";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button5_1.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ctrl";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "ctrl";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "ctrl";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ctrl";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button5_2 = keyboard_doby.querySelector('.keyboard_button5_2');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button5_2.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "win";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "win";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "win";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "win";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_1.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "win";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "win";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "win";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ctrl";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button5_3 = keyboard_doby.querySelector('.keyboard_button5_3');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button5_3.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "alt";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "alt";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "alt";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "alt";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_3.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "alt";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "alt";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "alt";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ctrl";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button5_4 = keyboard_doby.querySelector('.keyboard_button5_4');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button5_4.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = " ";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = " ";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = " ";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = " ";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_4.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = " ";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = " ";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = " ";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = " ";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button5_5 = keyboard_doby.querySelector('.keyboard_button5_5');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button5_5.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "alt";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "alt";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "alt";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "alt";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_5.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "alt";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "alt";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "alt";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ctrl";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button5_6 = keyboard_doby.querySelector('.keyboard_button5_6');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button5_6.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "◄";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "◄";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "◄";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "◄";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_6.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "◄";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "◄";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "◄";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "◄";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button5_7 = keyboard_doby.querySelector('.keyboard_button5_7');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button5_7.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "▼";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "▼";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "▼";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "▼";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_7.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "▼";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "▼";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "▼";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "▼";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button5_8 = keyboard_doby.querySelector('.keyboard_button5_8');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button5_8.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "►";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "►";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "►";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "►";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button2_8.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "►";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "►";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "►";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "►";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');

let keyboard_button5_9 = keyboard_doby.querySelector('.keyboard_button5_9');
ru = document.createElement('span');
ru.className = "ru";
keyboard_button5_9.append(ru);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ctrl";
ru.append(casedown);        
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "ctrl";
ru.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "ctrl";
ru.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ctrl";
ru.append(shiftcaps);
shiftcaps.classList.add('hidden');
                    
en = document.createElement('span');
en.className = "en";
keyboard_button5_9.append(en);
casedown = document.createElement('span');
casedown.className = "casedown";
casedown.textContent = "ctrl";
en.append(casedown);
casedown.classList.add('hidden')
caseUp = document.createElement('span');
caseUp.className = "caseUp";
caseUp.textContent = "ctrl";
en.append(caseUp);
caseUp.classList.add('hidden');
caps = document.createElement('span');
caps.className = "caps";
caps.textContent = "ctrl";
en.append(caps);
caps.classList.add('hidden');
shiftcaps = document.createElement('span');
shiftcaps.className = "shiftcaps";
shiftcaps.textContent = "ctrl";
en.append(shiftcaps);
shiftcaps.classList.add('hidden');


keyboard_button1_1.addEventListener('click', change);
function change (event) {
    let content = ""
    for (i=0; i<4; i++) {
        if (!keyboard_button1_1.firstChild.childNodes[i].classList.contains('hidden')) {
            content += keyboard_button1_1.firstChild.childNodes[i].textContent
            console.log(content)}
    }
    for (i=0; i<4; i++) {
        if (!keyboard_button1_1.lastChild.childNodes[i].classList.contains('hidden')) {
            content += keyboard_button1_1.firstChild.childNodes[i].textContent
            console.log(content)}
    }
    textarea.value += content
}

